[google]
type= "service_account"
project_id= "nathally-dashboard"
private_key_id= "9105d50d6341e43f81b9d74239328c09ffa01bb8"
private_key= "-----BEGIN PRIVATE KEY-----\nMIIEvwIBADANBgkqhkiG9w0BAQEFAASCBKkwggSlAgEAAoIBAQC1wLbiT2gADigG\nLKW7ZIZo68dAzd0AvzfGPs4KE+tEgwFZD69SwOnR+WNQ6viW0klAPJIwO39naz6u\nxVUbr03DT3FnpxtEPbO3pD8UnfcggGs3iGssJ3qHCkj3lyPYvAFzgt7SNyzC7Ekt\nKdGqSpn7J5pbMzuJ0SuNjoTBJ2Swvlpg7EK/p+iU/Jb8jA7EO0SOMfG94piCrxH8\n/8kY7nZdKMNiJHYk5xvRwiWwo0kg6wxKAgLtnPFxiOXBQZ2nEnWodaWVXvvaKdWY\n/EAE+nF/8ZnXsptooo3hTsbyUe29aQKqSyk9XAcpxsFtQkzAKzuuXHAD6SPDCf+V\nnc2w+agjAgMBAAECggEAVO3Yh6fTUTNMQJZcW1R9+kkysnV/7/lqdpiibtMf/MO6\nvYM2ydSbbiK65fTmdJOO5xVmumMTBaB3ifNr8aPZEors0yKi+yBZ+lYlo9ysveNE\nNo7ohZltB+0ma4uUlJJFm1RsCo79u5fuGcyQzKJPkazP1A38pEm5sEwIfLmLs4pz\nYnIUaH6eNFqBmQyzzgi1i5TOF5xs9GxQ1aBGgZGKfAoBq6QSpo0QXZ7wR37oGOHi\naTlZF7LuIYJBa9ERZjq3K5ACUajMS2nmDTQre5rpP9cqoJf2Az/nsSpOFaP1DC4W\ncjDkUY6cacC7iqhm0MxnXh/fBHt6GhRSiBkUVNwuAQKBgQD8LsNXcDhQwmvq8VVP\nHvTlmV0Ov/jnbQeUR2c1O6zIVsGvGdN9MIEiJw0oGHsA8WhFDUCxs6MoxanqYhD2\nyegt2Tb1TwH1MbwkXlkxXeTo7J+G1damlV42GeKegNW7cN5ZpUCIJ9/Vpcwplib2\nB/W1iWavIDTETvlSV8tgejAa+wKBgQC4gQcF1qIYVSrWacpNd0sn8t9fRtpn6mAG\nHpTdaX6R0t7whg+3U+YvWHSsfL7BbtNV/aj0hy732TWg1pvxkeVJXLGZQXSVVdon\nASwUZ+Zplstu1Fy0ITHLMopkXUWJXrSi3WPJdNNIUS1f1kV1RY6q+MLzrbcPSjbS\n/UG80DIe+QKBgQDKe42zDlLZXVIjQYT602NVWu+iITfsMdntD+vpjTGtZiN7waPT\nF/gHgQ2KTSWuWycakoqIZDE0UomcvQLb9MAs2ATNsJNk2Xs0RGEfR0G+WAe6zsXb\n2YDctaoFFHMIXpbZqdsHt+R8efRUy9Aaqcd67Ij7QkO7/6EmoYGVxGYNswKBgQC4\nDbbUwy0Gewd1xyjRqFxn6Ked4w+DNFJAKIe2bEOf8q0FYacR6fcpaeNSIkskqYrX\nMGk4LhbTlnIiFZSRIkqJqZddW+eSBYfO+yNe49r9oDkmQWCNLMQAgVV/E3CHvdsS\n0Sl3UTxn2tsZzKWTfCT7N5c7ASMpdI5GYfAPC93D+QKBgQCkKtxzcqplT6Ltkma1\nrMgs7uYoqmtB8rUyeO04djknanVb7+RlPoBTqcTUWVEh9Xiwbko9bUe/I3jMQxBE\nUMXPbPrD9oZSitt5LveNqD7BFTVK0QphXMrMvGffKmPN2+pu4xfDYxuCxC9J7Y+i\n6h30Jj8nrpUDRW/8ElCv14p4mg==\n-----END PRIVATE KEY-----\n"
client_email= "nathally-dashboard-api-1@nathally-dashboard.iam.gserviceaccount.com"
client_id= "109890418337110305701"
auth_uri= "https://accounts.google.com/o/oauth2/auth"
token_uri= "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url= "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url= "https://www.googleapis.com/robot/v1/metadata/x509/nathally-dashboard-api-1%40nathally-dashboard.iam.gserviceaccount.com"
universe_domain= "googleapis.com"

[access_tokens]
user_access_token = 'EAAOBMtxoGREBO37tDfsQwiEuUwqMvekKcor3XBcA9qvaqTqwD1sq5TK67WeulTPq2Hg6NZB6xBAK2MGrzBaQSSFPl1aQuYseQz33WuQ9QrNng6WewxFgGy0R36lAnllijV1ITaDINEpTSa38tVUZBAQyyPvzshPiuq1tyOgwiBRlYOZCxA3xgZDZD'
page_access_token = 'EAAOBMtxoGREBO2VvU6JjZAJG49HcMbdAlZBe2iJd7ev3CgXhXjaYMxl6oHyMl3799un2rs5R6RPsiJBK87dg2ZCxLbXugZBYCoevi9cvkKN1g7SKbHAVnW8MY5lZCXnVGPRzkT0P5HvX3IZBpLFHZArN5XTsEfvGZAZAboZBkDkr1v12AGIF4ZBFH2ZAKVjR0u5JKQZDZD'

[facebook]
page_id = '1060285064080786'

[instagram]
instagram_user_id = '17841408502224892'

[adaccount]
adaccount_account_id = "263939745137719"
adaccount_id         = "act_263939745137719"